### ISSUE TITLE
[8.6 Release Issues] Graphical and Console wait login are mixed up sometimes

### ISSUE THREAD

**Issue by lumarel** [rocky-linux/os-autoinst-distri-rocky#81]
**Describe the bug**
We have sometimes the _graphical_wait_login and _console_wait_login mixed up, i.e. in
-  rocky-8.6-dvd-iso-x86_64-Build-minimal-20220512.125057.0-install_default@uefi is graphical:
![image](https://user-images.githubusercontent.com/42647570/168185520-d4dc4fdc-dc73-4927-80d4-62e5494b5121.png)
-  rocky-8.6-universal-x86_64-Build-universal-20220512.223204.0-install_custom_gui_software_raid@64bit is console:
![image](https://user-images.githubusercontent.com/42647570/168185561-9124a933-39c1-4b9a-a715-98d261389d4c.png)

**To Reproduce**
run one of the test suites:
- minimal dvd-iso
- universal

that might also occur in others but these are pretty good examples

**Expected behavior**
correctly handle the addition of the wait

**Additional context**
If the tests run too long, just send me a message, and I will look to grab the rest of the occurrences

**Comment by akatch** [comment]
The `install_default` failure case still exists in `develop` after the 8.6 merge, so *not* closing this. Working on a fix.

**Comment by akatch** [comment]
Having investigated this further, I believe that the behavior we're seeing is expected. The `install_default` test suite is intended to verify that the default package set for each flavor. For both dvd-iso and boot-iso flavors, the default package set is `graphical-server`, which is expected to have a post-install graphical login. When the `server` package set is specified, no graphical login is available, thus the test fails. We should probably avoid calling `install_default` with a PACKAGE_SET provided, since the nature of the test is to expect a particular package set already.

**Comment by lumarel** [comment]
> Having investigated this further, I believe that the behavior we're seeing is expected. The `install_default` test suite is intended to verify that the default package set for each flavor. For both dvd-iso and boot-iso flavors, the default package set is `graphical-server`, which is expected to have a post-install graphical login. When the `server` package set is specified, no graphical login is available, thus the test fails. We should probably avoid calling `install_default` with a PACKAGE_SET provided, since the nature of the test is to expect a particular package set already.

Unfortunately this is not true for some of the tests, because for some the name already suggests the test being in text / graphical mode, and I have a history of how they have run in the past as well, for some.
It looks to me like the selection in the main.pm works not correctly there 🤔

**Comment by tcooper** [comment]
Resolved in #125 and #127... closing.
